divided_kingdom/apps/player/urls.py
from django.conf.urls import patterns, url
from divided_kingdom.apps.core.patterns import ID
from divided_kingdom.apps.player import views


urlpatterns = patterns(
    "",
    url(r"^/new$", views.create, name="new"),
    url(r"^/(?P<id>%s)$" % ID, views.detail, name="detail"),
)

divided_kingdom/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from divided_kingdom.apps.site import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'divided_kingdom.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r"^authentication", include("divided_kingdom.apps.authentication.urls", namespace="authentication")),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r"^site/", include("divided_kingdom.apps.site.urls", namespace="site")),
    url(r"^player", include("divided_kingdom.apps.player.urls", namespace="player")),
    url(r'^npc', include('divided_kingdom.apps.npc.urls', namespace="npc")),
    url(r"^game/", include("divided_kingdom.apps.game.urls.game", namespace="game")),
    url(r"^item", include("divided_kingdom.apps.item.urls", namespace="item")),


    url(r"^phase", include("divided_kingdom.apps.phase.urls", namespace="phase")),

    url(r"^$", views.index, name="index"),
)

divided_kingdom/apps/player/models.py
from django.contrib.auth.models import User
from divided_kingdom.apps.core.game_settings import STARTING_GOLD, BASE_HEALTH, BASE_STAMINA, STARTING_ACTION_POINTS, \
    STARTING_SKILL_POINTS, BASE_ATTACK, BASE_DEFENSE, BASE_SPEED
from divided_kingdom.apps.core.models import AuditModel, GENDER
from django.db import models

from divided_kingdom.apps.location.models import Route, Location



PLAYER_STATUS = (
    ("C", "Combat",),
    ("E", "Event",),
    ("L", "Location",),
    ("R", "Route",),
)

STAT = (
    ("STR", "strength",),
    ("DEX", "dexterity",),
    ("CON", "constitution",),
    ("INT", "intelligence",),
    ("WIL", "will_power",),
    ("PER", "perception",),
    ("ARC", "arcane_power",),
    ("PRE", "presence",),
    ("MAN", "manipulation",),
    ("ATT", "attack",),
    ("DEF", "defense",),
    ("SPD", "speed",),
    ("HP", "current_health",),
    ("ST", "current_stamina",),
    ("THP", "total_health",),
    ("TST", "total_stamina",),
)

class MotivatingForce(AuditModel):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __unicode__(self):
        return self.name


class Player(AuditModel):
    name = models.CharField(max_length=30)
    user = models.ForeignKey(User, null=True, blank=True, related_name="players")
    gender = models.CharField(max_length=1, choices=GENDER)
    age = models.IntegerField(default=0)
    xp = models.IntegerField(default=0)
    level = models.IntegerField(default=1)
    gold = models.IntegerField(default=STARTING_GOLD)

    action_points = models.IntegerField(default=STARTING_ACTION_POINTS)
    skill_points = models.IntegerField(default=STARTING_SKILL_POINTS)

    total_health = models.IntegerField(default=BASE_HEALTH)
    current_health = models.IntegerField(default=BASE_HEALTH)
    total_stamina = models.IntegerField(default=BASE_STAMINA)
    current_stamina = models.IntegerField(default=BASE_STAMINA)

    strength = models.IntegerField(default=0)
    dexterity = models.IntegerField(default=0)
    constitution = models.IntegerField(default=0)
    intelligence = models.IntegerField(default=0)
    will_power = models.IntegerField(default=0)
    perception = models.IntegerField(default=0)
    arcane_power = models.IntegerField(default=0)
    presence = models.IntegerField(default=0)
    manipulation = models.IntegerField(default=0)

    attack = models.IntegerField(default=BASE_ATTACK)
    defense = models.IntegerField(default=BASE_DEFENSE)
    speed = models.IntegerField(default=BASE_SPEED)

    motivating_force = models.ForeignKey(MotivatingForce, null=True, blank=True)

    route = models.ForeignKey(Route, null=True, blank=True)
    location = models.ForeignKey(Location, null=True, blank=True)
    distance_marker = models.IntegerField(default=0)

    status = models.CharField(max_length=1, choices=PLAYER_STATUS, default='L')

    weapon = models.ForeignKey("item.Item", null=True, blank=True, related_name="+")
    off_hand = models.ForeignKey("item.Item", null=True, blank=True, related_name="+")

    head = models.ForeignKey("item.Item", null=True, blank=True, related_name="+")
    chest = models.ForeignKey("item.Item", null=True, blank=True, related_name="+")
    legs = models.ForeignKey("item.Item", null=True, blank=True, related_name="+")
    feet = models.ForeignKey("item.Item", null=True, blank=True, related_name="+")
    right_hand = models.ForeignKey("item.Item", null=True, blank=True, related_name="+")
    left_hand = models.ForeignKey("item.Item", null=True, blank=True, related_name="+")

    gloves = models.ForeignKey("item.Item", null=True, blank=True, related_name="+")
    mount = models.ForeignKey("item.Item", null=True, blank=True, related_name="+")


    def __unicode__(self):
        return self.name

    def adjust_health(self, amount):
        self.current_health += amount

        if self.current_health < 0:
            self.current_health = 0

        if self.current_health > self.total_health:
            self.current_health = self.total_health

        result = "You {0} <span class='health'>{1} health</span>.".format(
            "gain" if amount > 0 else "lose", abs(amount))

        return result

    def adjust_stamina(self, amount):
        self.current_stamina += amount

        if self.current_stamina < 0:
            self.current_stamina = 0

        if self.current_stamina > self.total_stamina:
            self.current_stamina = self.total_stamina

        result = "You {0} <span class='stamina'>{1} stamina</span>.".format(
            "gain" if amount > 0 else "lose", abs(amount))

        return result

    def adjust_stat(self, stat_code, amount):
        if stat_code == "STR":
            self.strength += amount
        elif stat_code == "DEX":
            self.dexterity += amount
        elif stat_code == "CON":
            self.constitution += amount
        elif stat_code == "INT":
            self.intelligence += amount
        elif stat_code == "WIL":
            self.will_power += amount
        elif stat_code == "ARC":
            self.arcane_power += amount
        elif stat_code == "PRE":
            self.presence += amount
        elif stat_code == "MAN":
            self.manipulation += amount
        elif stat_code == "ATT":
            self.attack += amount
        elif stat_code == "DEF":
            self.defense += amount
        elif stat_code == "SPD":
            self.speed += amount
        elif stat_code == "HP":
            self.adjust_health(amount)
        elif stat_code == "ST":
            self.adjust_stamina(amount)
        elif stat_code == "THP":
            self.total_health += amount
        elif stat_code == "TST":
            self.total_stamina += amount

divided_kingdom/apps/player/forms.py
from django import forms
from django.forms import model_to_dict
from divided_kingdom.apps.core.game_settings import BASE_HEALTH, BASE_STAMINA
from divided_kingdom.apps.player.models import GENDER, Player


class PlayerForm(forms.Form):
    name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={"class": "span3"}))
    gender = forms.ChoiceField(required=False, choices=GENDER)
    age = forms.IntegerField(min_value=17, max_value=75)

    def __init__(self, *args, **kwargs):
        self.instance = kwargs.pop("instance", None)
        self.user = kwargs.pop("user", None)

        super(PlayerForm, self).__init__(*args, **kwargs)

        if self.instance:
            self.initial = model_to_dict(self.instance)

    def clean_name(self):
        name = self.cleaned_data.get("name")

        if not self.is_edit and Player.objects.filter(name=name).exists():
            raise forms.ValidationError(
                "A player with this name already exists")

        return name

    @property
    def is_edit(self):
        return self.instance is not None

    def save(self):

        data = self.cleaned_data
        player = self.instance or Player()

        player.name = data.get("name")
        player.gender = data.get("gender")
        player.age = data.get("age")
        player.user = self.user
        player.xp = 0

        player.save()

        return player

divided_kingdom/apps/player/views.py
from annoying.functions import get_object_or_None
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, get_object_or_404
from django.template import RequestContext
from django.template.response import TemplateResponse
from divided_kingdom.apps.core.game_settings import STARTING_LOCATION_ID
from divided_kingdom.apps.game.helpers.helper import get_game_messages
from divided_kingdom.apps.item.models import Item
from divided_kingdom.apps.location.models import Location
from divided_kingdom.apps.player.forms import PlayerForm
from divided_kingdom.apps.player.models import Player
from divided_kingdom.apps.player.utils import new_player_setup


@login_required
def create(request):
    user = request.user

    if request.method == "POST":
        form = PlayerForm(data=request.POST, user=user)

        if form.is_valid():
            player = form.save()
            new_player_setup(player)

            return redirect(reverse("game:play"))
    else:
        form = PlayerForm(user=user)

    context = RequestContext(request, {
        "form": form,
    })

    return TemplateResponse(request, "player/new.html", context)


@login_required
def detail(request, id):
    player = get_object_or_404(Player, pk=id)

    items = Item.objects.filter(player=player)

    context = RequestContext(request, {
        "player": player,
        "items": items,
        "game_messages": get_game_messages(player),
    })

    return TemplateResponse(request, "player/detail.html", context)

divided_kingdom/apps/player/templates/player/detail.html
{% extends "internal.html" %}

{% block content %}

  <h2>{{ player.name }}</h2>



  {% for game_message in game_messages %}
    <p>{{ game_message.message|safe }}</p>
  {% endfor %}

  <div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#stats" role="tab" data-toggle="tab">Stats</a>
      </li>
      <li role="presentation">
        <a href="#equip" role="tab" data-toggle="tab">Equipment</a>
      </li>
      <li role="presentation">
        <a href="#inventory" role="tab" data-toggle="tab">Inventory</a>
      </li>
    </ul>

    <div class="tab-content">
      <div role="tabpanel" class="tab-pane fade in active" id="stats">
        {% include "player/stats.html" %}
      </div>
      <div role="tabpanel" class="tab-pane fade" id="equip">
        {% include "player/equipment.html" %}
      </div>
      <div role="tabpanel" class="tab-pane fade" id="inventory">
        <h4>Inventory</h4>
        {% include "item/inventory_list.html" %}
      </div>
    </div>
  </div>



{% endblock %}

divided_kingdom/apps/player/templates/player/equipment.html
{% load apps_item %}
<h4>Equipment</h4>

<div>Current Weapon: {{ player.weapon.name }}</div>

<div class="panel panel-default pull-left" style="width: 300px;margin-right: 10px;">
  <div class="panel-heading">Armor</div>
  <table class="table">
    <tr>
      <td>
        {% display_equipment "Head" player.head %}
      </td>
    </tr>
    <tr>
      <td>
        {% display_equipment "Chest" player.chest %}
      </td>
    </tr>
    <tr>
      <td>
        {% display_equipment "Gloves" player.gloves %}
      </td>
    </tr>
    <tr>
      <td>
        {% display_equipment "Legs" player.legs %}
      </td>
    </tr>
    <tr>
      <td>
        {% display_equipment "Feet" player.feet %}
      </td>
    </tr>
    <tr>
      <td>
        {% display_equipment "Mount" player.mount %}
      </td>
    </tr>
    <tr>
      <td>
        {% display_equipment "Right Hand" player.right_hand %}
      </td>
    </tr>
    <tr>
      <td>
        {% display_equipment "Left Hand" player.left_hand %}
      </td>
    </tr>
  </table>
</div>

divided_kingdom/apps/player/templates/player/header_info.html
{% load apps_game %}

<div style="width:360px;">
  <div class="pull-left">
    <img src="{{ STATIC_URL }}images/blank_avatar_male_small.jpg" style="border:1px solid black;margin: 2px;height: 44px;">
  </div>
  <div class="right">
    <a class="player-name" href="{% url "player:detail" player.pk %}">{{ player.name }}</a>



    <div style="font:10px verdana; padding:2px;color:white;">
      <table>
        <tr>
          <td>
             {% indicator_bar "HP" 100 player.current_health player.total_health "red" %}
          </td>
          <td>
            {% indicator_bar "ST" 100 player.current_stamina player.total_stamina "green" %}
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

divided_kingdom/apps/player/templates/player/new.html
{% extends "internal.html" %}
{% load bootstrap3 %}

{% block content %}

 <form action="{% url 'player:new' %}"
        method="post" role="form" class="form-horizontal">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}

    {% buttons %}
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">
        <span class="fa fa-user"></span> Create Character
      </button>
    </div>
    {% endbuttons %}
  </form>

{% endblock %}

divided_kingdom/apps/player/templates/player/stats.html
<h4>Player Stats</h4>

<div class="panel panel-default pull-left" style="width: 260px;margin-right: 10px;">
  <div class="panel-heading">Player Status</div>
  <table class="table">
    <tr>
      <td class='numeric' width="110">Health</td>
      <td class='numeric' width="50">{{ player.current_health }} / {{ player.total_health }}</td>
    </tr>
    <tr>
      <td class='numeric' width="110">Stamina</td>
      <td class='numeric' width="50"> {{ player.current_stamina }} / {{ player.total_stamina }}</td>
    </tr>
    <tr>
      <td class='numeric' width="110">XP</td>
      <td class='numeric' width="50">{{ player.xp }}</td>
    </tr>
    <tr>
      <td class='numeric' width="110">Level</td>
      <td class='numeric' width="50">{{ player.level }}</td>
    </tr>
    <tr>
      <td class='numeric' width="110">Gender</td>
      <td class='numeric' width="50"> {{ player.get_gender_display }}</td>
    </tr>

  </table>
</div>


<div class="panel panel-default pull-left" style="width: 160px;">
  <div class="panel-heading">Stats</div>
  <table class="table">
    <tr>
      <td class='numeric' width="110">Strength</td>
      <td class='numeric' width="50">{{ player.strength }}</td>
    </tr>

    <tr>
      <td class='numeric'>Dexterity</td>
      <td class='numeric'>{{ player.dexterity }}</td>
    </tr>

    <tr>
      <td class='numeric'>Constitution</td>
      <td class='numeric'>{{ player.constitution }}</td>
    </tr>

    <tr>
      <td class='numeric'>Intelligence</td>
      <td class='numeric'>{{ player.intelligence }}</td>
    </tr>

    <tr>
      <td class='numeric'>Will Power</td>
      <td class='numeric'>{{ player.will_power }}</td>
    </tr>

    <tr>
      <td class='numeric'>Perception</td>
      <td class='numeric'>{{ player.perception }}</td>
    </tr>

    <tr>
      <td class='numeric'>Arcane Power</td>
      <td class='numeric'>{{ player.arcane_power }}</td>
    </tr>

    <tr>
      <td class='numeric'>Presence</td>
      <td class='numeric'>{{ player.presence }}</td>
    </tr>

    <tr>
      <td class='numeric'>Manipulation</td>
      <td class='numeric'>{{ player.manipulation }}</td>
    </tr>

    <tr>
      <td class='numeric'>Attack</td>
      <td class='numeric'>{{ player.attack }}</td>
    </tr>

    <tr>
      <td class='numeric'>Defense</td>
      <td class='numeric'>{{ player.defense }}</td>
    </tr>

    <tr>
      <td class='numeric'>Speed</td>
      <td class='numeric'>{{ player.speed }}</td>
    </tr>
  </table>
</div>